// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EmailTestController from "./email_test_controller"
application.register("email-test", EmailTestController)

import FavouritesButtonController from "./favourites_button_controller"
application.register("favourites-button", FavouritesButtonController)

import FunFactController from "./fun_fact_controller"
application.register("fun-fact", FunFactController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInCommentController from "./insert_in_comment_controller"
application.register("insert-in-comment", InsertInCommentController)

import LoadingPageController from "./loading_page_controller"
application.register("loading-page", LoadingPageController)

import NavbarActiveController from "./navbar_active_controller"
application.register("navbar-active", NavbarActiveController)

import RefreshNewsController from "./refresh_news_controller"
application.register("refresh-news", RefreshNewsController)

import SelectedTopicsController from "./selected_topics_controller"
application.register("selected-topics", SelectedTopicsController)

import SwiperJsController from "./swiper_js_controller"
application.register("swiper-js", SwiperJsController)

import SwiperQuestionsController from "./swiper_questions_controller"
application.register("swiper-questions", SwiperQuestionsController)
