// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EmailTestController from "./email_test_controller"
application.register("email-test", EmailTestController)

import FavouritesButtonController from "./favourites_button_controller"
application.register("favourites-button", FavouritesButtonController)

import FunFactController from "./fun_fact_controller"
application.register("fun-fact", FunFactController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInCommentController from "./insert_in_comment_controller"
application.register("insert-in-comment", InsertInCommentController)

import LoadingPageController from "./loading_page_controller"
application.register("loading-page", LoadingPageController)

import LogoFadeController from "./logo_fade_controller"
application.register("logo-fade", LogoFadeController)

import ModalNewCardController from "./modal_new_card_controller"
application.register("modal-new-card", ModalNewCardController)

import NavbarActiveController from "./navbar_active_controller"
application.register("navbar-active", NavbarActiveController)

import QuestionSliderController from "./question_slider_controller"
application.register("question-slider", QuestionSliderController)

import RefreshNewsController from "./refresh_news_controller"
application.register("refresh-news", RefreshNewsController)

import ScrollLampController from "./scroll_lamp_controller"
application.register("scroll-lamp", ScrollLampController)

import SelectedTopicsController from "./selected_topics_controller"
application.register("selected-topics", SelectedTopicsController)

import ShowSliderController from "./show_slider_controller"
application.register("show-slider", ShowSliderController)

import SwiperJsController from "./swiper_js_controller"
application.register("swiper-js", SwiperJsController)

import SwiperQuestionsController from "./swiper_questions_controller"
application.register("swiper-questions", SwiperQuestionsController)
