// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavouritesButtonController from "./favourites_button_controller"
application.register("favourites-button", FavouritesButtonController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarActiveController from "./navbar_active_controller"
application.register("navbar-active", NavbarActiveController)

import TopicErrorController from "./topic_error_controller"
application.register("topic-error", TopicErrorController)
